# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Constitución de Chile
email: edu.rh90@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  En este sitio puedes leer la Constitución de Chile, ver los detalles
  de las distintas leyes que lo han modificado y compartir links directos
  a las versiones de los artículos que te interesan. Puedes
  colaborar en https://github.com/opensourcechile/constitucion
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leyabierta.cl" # the base hostname & protocol for your site, e.g. http://example.com
github_username: opensourcechile

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - data
  - venv
  - scripts
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics
google_analytics: UA-152972968-1
